export const langs = {
  ka: {
    home: {
      introPage: {
        navLinkTitle: "მთავარი",
        h1: "ფიტნეს დარბაზი - Fit Factory",
        p: "აჯსცბა ასჯც ოჯ აოდ ვჯ ო ოადჯცვ ო აკდვ ასდვ ოდჯვ ოადც კა აკ ვპად კადკ ცაჯც ჯოა ა",
        link: "შემოგვიერთდი",
        aboutUs: {
          btnName: "ჩვენს შესახებ",
          sectionName: "ჩვენს შესახებ",
          h3First: "დააფასე ",
          h3Second: "შენი სხეული, რადგან მხოლოდ ერთი გაქვს",
          div: "ასჰდჯას  ისდჯნ აკსფნ ადიფნასი ასნფაჯნ ასკმასკ დმა ადკფჯადიჯფიაჯ ადოჯფ ოად ანდფადნფია ადფ კაოდფ  ადფჯია დფნ აფკ ადლფ ადლფა ადფნ ადფ ჯი ჯიჯ ჯი იჯ",
          h5: {
            first: "უფასო WI-FI",
            second: "+3 ტრენერი",
            third: "20%-იანი ფასდაკლება",
            forth: "საუკეთესო საზოგადოება",
            fifth: "ექპერტები",
          },
        },
        pilates: {
          h4First: "პილატეს ",
          h4Second: "ჯგუფური ვარჯიში",
          p: "აჯსნდ აოჯფ აკფნაფ  აოკდფ აოანფკასნ აფო აფჯა  აფკა სოფკოაჯფა ფჯასფოაჯ აოფჯაჯფაოჯფაჯოფ ",
          link: "დეტალები",
        },
      },
      trainers: {
        navLinkTitle: "ტრენერები",
        trainer1: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "საბა გაჩეჩილაძე",
          jobDescription: "დირექტორი, ტრენერი",
        },
        trainer2: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "ალექსანდრე თევზაძე",
          jobDescription: "ტრენერი",
        },
        trainer3: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "ანა დოსტოევსკი",
          jobDescription: "ტრენერი",
        },
        trainer4: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "პილატე მაჭავარიანი",
          jobDescription: "ტრენერი",
        },
        trainer5: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "გიორგი კინწურაშვილი",
          jobDescription: "ტრენერი",
        },
      },
      pricing: {
        navLinkTitle: "ფასები",
        box1: {
          h5: "ერთ დღიანი პაკეტი",
          h4: "40",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        box2: {
          h5: "ერთ თვიანი პაკეტი",
          h4: "79",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        box3: {
          h5: "ერთ წლიანი პაკეტი",
          h4: "110",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        link: "დეტალები",
      },
    },
    blogs: {
      navLinkTitle: "ბლოგები",
      blog1: {
        blog1box: {},
        blog1page: {},
      },
      blog2: {},
      blog3: {},
      blog4: {},
      blog5: {},
      blog6: {},
    },
    contact: {
      navLinkTitle: "კონტაქტი",
      h2first: "ლოკაცია",
      h2second: "მოგვწერე მაილზე",
      h2third: "დაგვირეკე",
      form: {
        h3: "გამოგვიგზავნე შეტყობინება",
        btn: "გაგზავნა",
      },
    },
    startTrial: {
      navLinkTitle: "გაწევრიანდი",
      div: "გახდი წევრი",
      h1: "აიღე 1 თვიანი აბონომენტი დღეიდან",
      p: "აბს დსიჯ ჯსდოჯ ს სჯდ სიდ სიდჰს სჯოდ ჯსო სჯდსდ სჯდსჯ",
      error1: "სახელი აუცილებელია",
      error2: "ნომერი აუცილებელია",
      dateError: "დაწყების თარიღი აუცილებელია",
      datePlaceHolder: "* დაწყების თარიღი",
      btn: "გაგზავნა",
      total: "სულ:",
      select1: {
        option1: "გთხოვთ აირჩიეთ ვარიანტი",
        option2: "ტრენერის გარეშე",
        option3: "ტრენერი1 ",
        option4: "ტრენერი2 ",
        option5: "ტრენერი3 ",
      },
      select2: {
        option1: "გთხოვთ აირჩიეთ პაკეტი",
        option2: "პაკეტი1 ",
        option3: "პაკეტი2 ",
        option4: "პაკეტი3 ",
        option5: "პაკეტი4 ",
      },
    },
    footer: {
      p: "გამოგვყევით ინსტაგრამზე",
      h5first: "სამუშაო საათები",
      h5second: "დაგვეკონტაქტეთ",
      p1: "ორშაბათიდან პარასკევამდე: ",
      p2: "შაბათს: ",
      p3: "კვირას: ",
    },
  },
  en: {
    home: {
      introPage: {
        navLinkTitle: "Home",
        h1: "THE FIRST EVER MIXED MARTIAL ARTS WEBSITE TEMPLATE FOR US.",
        p: "Showcase your team, enlist students to classes, sell MMA products and grow your Mixed Martial Arts academy online.",
        link: "JOIN US",
        aboutUs: {
          btnName: "ABOUT US",
          sectionName: "ABOUT US",
          h3First: "RESPECT ",
          h3Second: "YOUR BODY, IT’S THE ONLY ONE YOU GET",
          div: "Aliquam erat volutpat. Donec elit nibh, luctus eu nisi eu, tempus condimentum ipsum. Nunc euismod viverra ante vel imperdiet. In pretium sagittis neque nec lacinia. Integer lorem odio, lobortis et odio eu, ullamcorper placerat arcu.",
          h5: {
            first: "FREE WI-FI",
            second: "+3 TRAINERS",
            third: "20% DISCOUNT",
            forth: "BEST COMMUNITY",
            fifth: "EXPERTS",
          },
        },
        pilates: {
          h4First: "PILATES ",
          h4Second: "GROUP EXCERCISE",
          p: "Supported by a network of early advocates contributors, and champions. We are gladly helping companies to get started",
          link: "SEE DETAILS",
        },
      },
      trainers: {
        navLinkTitle: "TRAINERS",
        trainer1: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          title: "Saba Gachechiladze",
          jobDescription: "Director, Trainer",
        },
        trainer2: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          title: "Aleksandre Chakvetadze",
          jobDescription: "Trainer",
        },
        trainer3: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          title: "Ana Dostoevski",
          jobDescription: "Trainer",
        },
        trainer4: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          title: "Pilate Machavariani",
          jobDescription: "Trainer",
        },
        trainer5: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          title: "Giorgi Kinwurashvili",
          jobDescription: "Trainer",
        },
      },
      pricing: {
        navLinkTitle: "PRICING",
        box1: {
          h5: "ONE DAY TRIAL",
          h4: "40",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        box2: {
          h5: "ONE MONTH TRIAL",
          h4: "79",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        box3: {
          h5: "ONE YEAR TRIAL",
          h4: "110",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        link: "SEE DETAILS",
      },
    },
    blogs: {
      navLinkTitle: "Blogs",
      blog1: {
        blog1box: {},
        blog1page: {},
      },
      blog2: {},
      blog3: {},
      blog4: {},
      blog5: {},
      blog6: {},
    },
    contact: {
      navLinkTitle: "CONTACT",
      h2first: "LOCATION",
      h2second: "CONTACT US",
      h2third: "CALL US",
      form: {
        h3: "SEND US A MESSAGE",
        btn: "Send",
      },
    },
    startTrial: {
      navLinkTitle: "Start-Trial",
      div: "BECOME A MEMBER",
      h1: "START YOUR 5 DAY TRIAL MEMBERSHIP TODAY",
      p: "Aliquam aliquet pretium sagittis est. Eleifend netus diam sit malesuada. Arcu, amet sem gravida sit arcu.",
      error1: "Name Is Required",
      error2: "Number Is Required",
      dateError: "Start Date is Required",
      datePlaceHolder: "* Start Date",
      btn: "SUBMIT",
      total: "TOTAL ",
      select1: {
        option1: "Please Select an Option",
        option2: "No Trainer",
        option3: "Trainer1 ",
        option4: "Trainer2 ",
        option5: "Trainer3 ",
      },
      select2: {
        option1: "Please Select Trial",
        option2: "Trial1 ",
        option3: "Trial2 ",
        option4: "Trial3 ",
        option5: "Trial4 ",
      },
    },
    footer: {
      p: "FOLLOW US ON INSTAGRAM",
      h5first: "OPEN HOURS",
      h5second: "CONTACT US",
      p1: "Monday To Friday: ",
      p2: "Saturday: ",
      p3: "Sunday: ",
    },
  },
};
