import { blogList, blogListEn } from "./config";

export const langs = {
  ka: {
    home: {
      introPage: {
        navLinkTitle: "მთავარი",
        navLinkClassName: "nav-link-ka",
        navArrowClassName: "nav-right-arrow-svg-ka",
        landingTiTleLine: "landing-title-line-ka",
        h1: "ფიტნეს დარბაზი -",
        h12: " Fit Factory",
        h1ClassName: "landing-title-ka",
        h12ClassName: "landing-span-ka",
        p: "ძვირფასო მომხმარებლებო, განვაახლეთ პროდუქცია დაკავშირებული რეგულავიების და უსაფრთხოების ნორმების სრული დაცვით ვაგრძელებთ მუშაობას",
        pClassName: "landing-text-ka",
        link: "შემოგვიერთდი",
        linkClassName: "btn-ka btn-1-ka",
        aboutUs: {
          infoWrapperClassName: "info-wrapper-top-ka info-wrapper-top",
          btnName: "ჩვენს შესახებ",
          btnClassName: "btn-2-ka btn-ka",
          sectionName: "ჩვენს შესახებ",
          sectionNameClassName: "about-title-text-ka",
          h3First: "დააფასე ",
          h3FirstClassName: "info-snap-ka",
          h3Second: "შენი სხეული, რადგან მხოლოდ ერთი გაქვს",
          h3SecondClassName: "info-title-ka",
          lineClassName: "info-line-ka",
          div: "ვფიქრობ ამ ვიდეოში აღმდგენიც უნდა ჩაგესვათ იმიტო რო თუ ორგანიზმს არ შეუძლია და მას ძალით ამუშავებ პრევორქაუთ დანამატით ჩათვალე რო აღდგენასაც მეტი დრო დაჭირდება.",
          divClassName: "info-text-ka",
          h5: {
            ClassName: "info-content-h5-ka",
            first: "უფასო WI-FI",
            second: "+3 ტრენერი",
            third: "20%-იანი ფასდაკლება",
            forth: "საუკეთესო საზოგადოება",
            fifth: "ექპერტები",
          },
        },
        pilates: {
          h4First: "პილატეს ",
          h4firstClassName: "pilates-title-ka",
          h4secondClassName: "pilates-span-ka",
          h4Second: "ჯგუფური ვარჯიში",
          p: "წიგნი ეხება თანამედროვე ქართული ლიტერატურის საკითხებს მეოცე საუკუნის პირველი ნახევრიდან, საბჭოური კულტურული პოლიტიკის დამკვიდრებიდან დღემდე. ",
          link: "დეტალები",
          linkClassName: "pilates-link-ka",
        },
      },
      trainers: {
        navLinkTitle: "ტრეინერები",
        trainersClassName: "trainers-main-title-ka",
        trainer1: {
          text: "დიდი ტექსტები ღლის  და მას არავინ არ კითხულობს. ამის საპირისპირო მოსაზრებაა  ის, რომ ბლოგი უნდა იყოს ვრცელი და სრულყოფილი. რომელი ამათგან სწორი",
          title: "საბა გაჩეჩილაძე",
          text1ClassName: "slider-text-5-ka slider-text-ka",
          title1ClassName: "carousel-info-title-ka carousel-1-title-ka",
          jobDescription: "დირექტორი, ტრენერი",
        },
        trainer2: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "ალექსანდრე თევზაძე",
          text2ClassName: "slider-text-5-ka slider-text-ka",
          title2ClassName: "carousel-info-title-ka carousel-2-title-ka",
          jobDescription: "ტრენერი",
        },
        trainer3: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "ანა დოსტოევსკი",
          text3ClassName: "slider-text-5-ka slider-text-ka",
          title3ClassName: "carousel-info-title-ka carousel-3-title-ka",
          jobDescription: "ტრენერი",
        },
        trainer4: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "პილატე მაჭავარიანი",
          text4ClassName: "slider-text-5-ka slider-text-ka",
          title4ClassName: "carousel-info-title-ka carousel-4-title-ka",
          jobDescription: "ტრენერი",
        },
        trainer5: {
          text: "აკდფნადკ ადფნაიდ აინფანც აოდვმადოვ მადოვსფნვ ოდა ვოსდ ვმოსსოდვჯ სდოვკ სდოვსოდვჯსდო ვსდსოდვ",
          title: "გიორგი კინწურაშვილი",
          text5ClassName: "slider-text-5-ka slider-text-ka",
          title5ClassName: "carousel-info-title-ka carousel-5-title-ka",
          jobDescription: "ტრენერი",
        },
      },
      pricing: {
        navLinkTitle: "ფასები",
        box1: {
          h5: "ერთ დღიანი პაკეტი",
          h5ClassName: "date-of-pricingBox-ka center-date-price-ka",
          text5ClassName: "slider-text-5-ka slider-text-ka",
          h4: "40",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        box2: {
          h5: "ერთ თვიანი პაკეტი",
          h5ClassName: "date-of-pricingBox-ka center-date-price-ka",
          text5ClassName: "slider-text-5-ka slider-text-ka",
          h4: "79",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        box3: {
          h5: "ერთ წლიანი პაკეტი",
          h5ClassName: "date-of-pricingBox-ka center-date-price-ka",
          text5ClassName: "slider-text-5-ka slider-text-ka",
          h4: "110",
          p1: "მორგებული განრიგი",
          p2: "გამოცდილი ტრენერები",
          p3: "მორგებული განრიგი",
        },
        link: "დეტალები",
        linkClassName: "price-btn-ka",
        lastLinkClassName: " last-price-btn",
      },
    },
    blogs: {
      navLinkTitle: "ბლოგები",
      blogLang: blogList,
    },
    contact: {
      navLinkTitle: "კონტაქტი",
      h2first: "ლოკაცია",
      h2second: "მოგვწერე მაილზე",
      h2third: "დაგვირეკე",
      form: {
        h3: "გამოგვიგზავნე შეტყობინება",
        btn: "გაგზავნა",
      },
    },
    startTrial: {
      navLinkTitle: "გაწევრიანდი",
      div: "გახდი წევრი",
      h1: "აიღე 1 თვიანი აბონომენტი დღეიდან",
      p: "აბს დსიჯ ჯსდოჯ ს სჯდ სიდ სიდჰს სჯოდ ჯსო სჯდსდ სჯდსჯ",
      error1: "სახელი აუცილებელია",
      error2: "ნომერი აუცილებელია",
      dateError: "დაწყების თარიღი აუცილებელია",
      datePlaceHolder: "* დაწყების თარიღი",
      btn: "გაგზავნა",
      total: "სულ:",
      select1: {
        option1: "გთხოვთ აირჩიეთ ვარიანტი",
        option2: "ტრენერის გარეშე",
        option3: "ტრენერი1 ",
        option4: "ტრენერი2 ",
        option5: "ტრენერი3 ",
      },
      select2: {
        option1: "გთხოვთ აირჩიეთ პაკეტი",
        option2: "პაკეტი1 ",
        option3: "პაკეტი2 ",
        option4: "პაკეტი3 ",
        option5: "პაკეტი4 ",
      },
    },
    footer: {
      p: "გამოგვყევით ინსტაგრამზე",
      pClassName: "footer-p-social-ka",
      h5first: "სამუშაო საათები",
      h5firstClassName: "footer-left-title-ka",
      h5second: "დაგვეკონტაქტეთ",
      h5secondClassName: "footer-right-title-ka",
      h4FooterClassName: "footer-logo-ka",
      footerMiddleClassName: "footer-middle-ka",
      p1: "ორშაბათიდან პარასკევამდე: ",
      p2: "შაბათს: ",
      p3: "კვირას: ",
      pBottomClassName: "p-footer-all",
      footerTop: "footer-top-ka",
    },
  },
  en: {
    home: {
      introPage: {
        navLinkTitle: "Home",
        navLinkClassName: "nav-link",
        navArrowClassName: "nav-right-arrow-svg",
        landingTiTleLine: "landing-title-line",
        h1: "THE FIRST EVER MIXED MARTIAL ARTS WEBSITE TEMPLATE FOR US.",
        h12: "",
        h1ClassName: "landing-title",
        h12ClassName: "landing-span",
        p: "Showcase your team, enlist students to classes, sell MMA products and grow your Mixed Martial Arts academy online.",
        pClassName: "landing-text",
        link: "JOIN US",
        linkClassName: "btn btn1",
        aboutUs: {
          infoWrapperClassName: "info-wrapper-top",
          btnName: "ABOUT US",
          btnClassName: "btn2 btn",
          sectionName: "ABOUT US",
          sectionNameClassName: "about-title-text",
          h3First: "RESPECT ",
          h3FirstClassName: "info-span",
          h3Second: "YOUR BODY, IT’S THE ONLY ONE YOU GET",
          h3SecondClassName: "info-title",
          lineClassName: "info-line",
          div: "Aliquam erat volutpat. Donec elit nibh, luctus eu nisi eu, tempus condimentum ipsum. Nunc euismod viverra ante vel imperdiet. In pretium sagittis neque nec lacinia. Integer lorem odio, lobortis et odio eu, ullamcorper placerat arcu.",
          divClassName: "info-text",
          h5: {
            ClassName: "info-content-h5",
            first: "FREE WI-FI",
            second: "+3 TRAINERS",
            third: "20% DISCOUNT",
            forth: "BEST COMMUNITY",
            fifth: "EXPERTS",
          },
        },
        pilates: {
          mainDivClassName: "pilates-top",
          h4First: "PILATES ",
          h4Second: "GROUP EXCERCISE",
          h4firstClassName: "pilates-title",
          h4secondClassName: "pilates-span",
          p: "Supported by a network of early advocates contributors, and champions. We are gladly helping companies to get started",
          link: "SEE DETAILS",
          linkClassName: "pilates-link",
        },
      },
      trainers: {
        navLinkTitle: "TRAINERS",
        trainersClassName: "trainers-main-title",
        trainer1: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          text1ClassName: "slider-text-1 slider-text",
          title1ClassName: "carousel-info-title carousel-1-title",
          title: "Saba Gachechiladze",
          jobDescription: "Director, Trainer",
        },
        trainer2: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          text2ClassName: "slider-text-2 slider-text",
          title2ClassName: "carousel-info-title carousel-2-title",
          title: "Aleksandre Chakvetadze",
          jobDescription: "Trainer",
        },
        trainer3: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          text3ClassName: "slider-text-3 slider-text",
          title3ClassName: "carousel-info-title carousel-3-title",
          title: "Ana Dostoevski",
          jobDescription: "Trainer",
        },
        trainer4: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          text4ClassName: "slider-text-4 slider-text",
          title4ClassName: "carousel-info-title carousel-4-title",
          title: "Pilate Machavariani",
          jobDescription: "Trainer",
        },
        trainer5: {
          text: "So thoughtful and wise, and vulnerable in sharing her own challenges with me. Dani is wonderful!",
          text5ClassName: "slider-text-5 slider-text",
          title5ClassName: "carousel-info-title carousel-5-title",
          title: "Giorgi Kinwurashvili",
          jobDescription: "Trainer",
        },
      },
      pricing: {
        navLinkTitle: "PRICING",
        box1: {
          h5: "ONE DAY TRIAL",
          h5ClassName: "date-of-pricingBox center-date-price",
          h4: "40",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        box2: {
          h5: "ONE MONTH TRIAL",
          h5ClassName: "date-of-pricingBox center-date-price",
          h4: "79",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        box3: {
          h5: "ONE YEAR TRIAL",
          h5ClassName: "date-of-pricingBox center-date-price",
          h4: "110",
          p1: "Personalized Training",
          p2: "Experience personalized training group",
          p3: "Group Fitness Access",
        },
        link: "SEE DETAILS",
        linkClassName: "price-btn",
        lastLinkClassName: " last-price-btn",
      },
    },
    blogs: {
      navLinkTitle: "Blogs",
      blogLang: blogListEn,
    },
    contact: {
      navLinkTitle: "CONTACT",
      h2first: "LOCATION",
      h2second: "CONTACT US",
      h2third: "CALL US",
      form: {
        h3: "SEND US A MESSAGE",
        btn: "Send",
      },
    },
    startTrial: {
      navLinkTitle: "Start-Trial",
      div: "BECOME A MEMBER",
      h1: "START YOUR 5 DAY TRIAL MEMBERSHIP TODAY",
      p: "Aliquam aliquet pretium sagittis est. Eleifend netus diam sit malesuada. Arcu, amet sem gravida sit arcu.",
      error1: "Name Is Required",
      error2: "Number Is Required",
      dateError: "Start Date is Required",
      datePlaceHolder: "* Start Date",
      btn: "SUBMIT",
      total: "TOTAL ",
      select1: {
        option1: "Please Select an Option",
        option2: "No Trainer",
        option3: "Trainer1 ",
        option4: "Trainer2 ",
        option5: "Trainer3 ",
      },
      select2: {
        option1: "Please Select Trial",
        option2: "Trial1 ",
        option3: "Trial2 ",
        option4: "Trial3 ",
        option5: "Trial4 ",
      },
    },
    footer: {
      p: "FOLLOW US ON INSTAGRAM",
      pClassName: "footer-p-social",
      h5first: "OPEN HOURS",
      h5firstClassName: "footer-left-title",
      h5second: "CONTACT US",
      h5secondClassName: "footer-right-title",
      h4FooterClassName: "footer-logo",
      footerMiddleClassName: "footer-middle",
      p1: "Monday To Friday: ",
      p2: "Saturday: ",
      p3: "Sunday: ",
      pBottomClassName: "",
      footerTop: "footer-top",
    },
  },
};
